name: Test

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Update pip
        run: python3 -m pip install --upgrade pip

      - name: Install
        run: python3 -m pip install .

      - name: Run tests
        run: python -m pytest
